print("_____________________")
print("nu grade calculator")
print("_____________________")
COSTANname = str(input("enter your name: "))
COSTANyear = str(input("enter your year: "))
COSTANsec = str(input("enter section: "))
COSTANRphgrade = float(input("INPUT YOUR RPH GRADE: "))
COSTANutsgrade = float(input("INPUT YOUR UTS GRADE: "))
COSTANStsgrade = float(input("INPUT YOUR STS GRADE: "))
COSTANperComgrade = float(input("INPUT YOUR PERCOM GRADE: "))
COSTANincomgrade = float(input("INPUT YOUR INCOM GRADE:"))
COSTANcomfungrade = float(input("INPUT YOUR COMFUN GRADE: "))
COSTANpatfitgrade = float(input("INPUT YOUR PATFIT GRADE: "))
COSTANTOTAL = COSTANRphgrade + COSTANutsgrade + COSTANStsgrade + COSTANperComgrade + COSTANincomgrade + COSTANcomfungrade + COSTANpatfitgrade
COSTANAVG = COSTANTOTAL / 7
print("______________________")
print("STUDENTS AVERAGE GRADE")
print("______________________")
print("RESULTS:")
print(COSTANname,COSTANyear,COSTANsec)
print("AVERAGE GRADE:", COSTANAVG)
